services:
  - type: web
    name: savepr-downloader
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
